version: '3.7'

services: 
    ghpage:
        image: mendhak/jekyll-site
        build: 
            context: .

        volumes:
            - ${PWD}:/srv/jekyll
        ports: 
            - "0.0.0.0:4000:4000"
